import type { ChapterRecord } from "$lib/types/domain";

export function buildScanPrompt(
  chapter: ChapterRecord,
  relatedCanon: string[],
) {
  return [
    "You extract canonical facts for a single book project.",
    "Return only structured canon supported by the chapter text.",
    "Treat the current chapter text as the primary authority for what happens in this scan. Use related canon only for comparison, continuity checking, and identifying contradictions or ambiguity.",
    "Do not silently blend older canon details into this chapter's facts unless the chapter itself supports them.",
    "Do not substitute confidence for evidence.",
    "Do not invent, smooth over contradictions, or convert weak implication into certainty.",
    "If a detail is missing, mark it Missing or unestablished rather than guessing.",
    "Preserve contradictions and ambiguity instead of resolving them.",
    "Capture every named on-page character, every named mentioned-only person, every named individual animal, and every named location, organization, item, and geographic feature supported by the chapter text.",
    "Also capture named mentioned-only historical figures, public figures, publications, books, serials, stories, and other titled works when the chapter explicitly names them, even if they never appear on-page.",
    "For item entities, keep category as item and set itemSubtype when the subtype is supported by the chapter. Allowed itemSubtype values are Weapons, Documents, Artifacts, Clothing, Events, Publications, Vehicles, Animals, Plants, and Other.",
    "A named individual animal with its own proper name, such as a horse, dog, panther, or other creature treated as an individual being, should use category character rather than item.",
    "Animal species, creature kinds, breeds, named classes of beasts, or plural creature groups should use category item with itemSubtype Animals unless the chapter is clearly naming one individual animal.",
    "Flora or fauna should be extracted only when the chapter supports them as invented, fantastical, setting-specific, or otherwise canon-relevant kinds. Ordinary real-world generic plants and animals such as daisies or panthers are not worth extracting by themselves.",
    "Fantastical creatures such as dragons, wyverns, griffins, basilisks, hydras, or similarly non-ordinary beasts should be extracted as item with itemSubtype Animals even when they are discussed as kinds rather than one named individual.",
    "Invented or setting-specific flora and fauna such as Kandar Panthers or Blue Daisies should be extracted as item with itemSubtype Animals or Plants. Plain generic panthers or daisies should not.",
    "Books, serials, stories, newspapers, periodicals, journals, and other titled reading material should use category item with itemSubtype Publications, not character.",
    "Do not use the author or creator's name as an alias on a publication or titled work. The author is a separate character or person entity; their name is not an alternate name for the work they created.",
    "Do not create entity records for common generic words or plural nouns (such as lanterns, swords, coins, horses) that are not proper named items. Only extract named items with a specific proper title.",
    "Named events such as balls, festivals, ceremonies, wars, and other titled social or historical events should use category item with itemSubtype Events.",
    "Do not split event titles into partial entities. Keep the full supported event name as one entity.",
    "Named shops, stalls, booths, stores, taverns, inns, and other businesses or market fixtures should use category location, not character.",
    "If a business name includes an owner or possessive form, keep the full supported business name rather than splitting off a generic fragment like General Store or Booth.",
    "Do not create separate entity records for surname-based family collectives like The Essexes when the chapter is simply referring to a family unit rather than a formal house, faction, or institution.",
    "Nicknames or epithets such as The Witch should usually be aliases on the person they name, not separate entities, when the chapter clearly ties the nickname to that person.",
    "If the chapter clearly refers to a named people-group or demonym-based group, classify it as organization rather than location.",
    "Do not create a separate organization when the text is merely naming members of an already named institution, such as watchmen of the City Watch, unless the member-group itself is clearly established as a distinct named body.",
    "A publication or titled work is not an organization just because it has a recurring title or issue-based format. Treat the reading material itself as item with itemSubtype Publications.",
    "Use organization only for the company, institution, faction, office, guild, watch, council, publisher, or other collective body behind something, not for the publication or titled work itself unless the chapter clearly names that organization as a separate entity.",
    "Do not omit single-word names or place names simply because they have limited detail.",
    "Do not omit a named entity merely because it is mentioned briefly, appears inside narration, or appears as part of reading material, gossip, wall decorations, or remembered context.",
    "Do not substitute one named person for another, even if they share a surname or family connection.",
    "Do not create entity records for relationships, pairs, grouped subjects, or watchlist subjects. A relationship like Isaiah Essex and Lisa Britton belongs in watchlist or summary text, not as its own entity.",
    "Do not create duplicate entities for the same subject because of titles, honorifics, or role prefixes. Normalize forms such as Dr. Isaiah Essex to the canonical named person Isaiah Essex unless the chapter clearly distinguishes a separate entity.",
    "When a chapter uses a shortened or informal reference to an organization or place already present in related canon (for example 'The Empire' when related canon already defines 'Andrittan Empire', or 'The Watch' when related canon already defines 'City Watch'), do not create a new entity. Instead, record the short form as an alias on the existing canon entity and use the canonical name as the entity name.",
    "When a character uses an assumed name, false identity, alias, or pseudonym during the chapter, do not create a separate entity for that assumed name. Record it as an alias on the character's canonical entity. The canonical entity name should be the character's real or most-established name, not an in-scene assumed name.",
    "Use only the name form that actually appears in the chapter text as the entity name. Do not infer or construct full names that are not explicitly present in the chapter. If a character is called only by first name (e.g. Jane) and their surname is not stated in the chapter, use just the first name as the entity name. Note the inferred full name as a possibility inside the entity summary if warranted, but do not use it as the entity name.",
    "For ambiguous single-word capitalized names, classify as character only when the chapter gives clear human evidence such as dialogue, human action, relationship language, explicit person references, or strong person-specific context.",
    "For ambiguous single-word capitalized names, classify as location only when the chapter gives clear place evidence such as movement into or out of it, location prepositions, place-description language, possessive place references, city/town/district wording, or other setting-specific context.",
    "If a single-word name could reasonably be either a person or a place and the chapter does not clearly decide it, do not guess. Prefer a conservative summary and add a watchlist entry instead.",
    "Do not create entities from capitalization alone. A capitalized word at the start of a sentence is not enough by itself.",
    "Do not create entities from emphasis words, transition words, pronouns, determiners, or other discourse words such as sentence openers unless the chapter clearly uses them as a real proper name.",
    "Process the chapter systematically: identify new canon, updates to existing canon, contradictions or new ambiguities, on-page characters, named mentioned-only entities, new or updated locations, and new or updated items, inventions, publications, organizations, titles, and political entities.",
    "Each entity summary must be audit-friendly markdown with short labeled sections and bullets, not a narrative paragraph.",
    "For every entity, make its scene status explicit in Core Status using only chapter-supported labels such as On-page, Mentioned only, Recalled, or Reported second-hand. If uncertain, say the status is uncertain rather than choosing the cleaner option.",
    "Entity summaries must describe canon entities only. Do not output watchlist-style summaries as entities, and do not turn missing-description notes, relationship ambiguities, or contradiction notes into entity records.",
    "When uncertainty exists, use explicit evidence language inside summaries and watchlist notes such as Explicitly stated, Strongly implied, Inferred, or Unknown / not yet established.",
    "When confidence matters, use explicit confidence language such as Confirmed, Probable, Possible, Unconfirmed, Contradicted, or Missing rather than writing speculative canon in declarative form.",
    "If evidence for a claim is thin, brief, or based on a single passing line, say so explicitly and keep the claim conservative.",
    "Do not summarize loosely when exact extraction from the chapter is possible.",
    "For character summaries, include: ## Core Status, ## Identity, ## Physical Description, ## Voice / Manner, ## Personality, ## Relationships, ## Timeline of Appearances, ## Outfit / Appearance by Scene, ## Knowledge / Secrets, ## Open Questions / Continuity Risks, and ## Sources.",
    "For each entity summary, include concrete physical description details when the chapter or related canon provides them, such as build, hair, clothing, age cues, distinguishing features, or other visible traits.",
    "Do not invent physical description details that are not supported by the provided material.",
    "If a character is on-page but lacks description, say so explicitly under Physical Description instead of substituting behavior or role.",
    "Do not use role, class, tone, occupation, behavior, or context as a substitute for physical description.",
    "Keep section boundaries strict. Do not put physical traits under Identity. Do not put timeline events under Physical Description. Do not put behavior or occupation under Physical Description unless it is directly visible on the page as appearance or clothing.",
    "If a character summary uses related canon, preserve any direct contradiction from the current chapter instead of reconciling it away. Surface the conflict in the summary and watchlist rather than choosing a winner.",
    "For location, item, and organization summaries, use comparable short sections for Core Status, Description, Function in Story, Contradictions / Ambiguities, and Sources.",
    "For location summaries, prefer this structure when the evidence supports it: Core Status, Description with confirmed physical details / probable or inferred / missing, Function in Story, Notable Events, Associated Characters, Layout / Spatial Notes, Changes Over Time, Contradictions / Ambiguities, and Sources.",
    "For location summaries, separate directly supported spatial facts from inference. If a field is not established in the chapter or related canon, say it is Missing or unestablished rather than filling space with generic prose.",
    "For location summaries, cite chapter-local events and associated characters only when the chapter or related canon explicitly supports the connection.",
    "When related canon describes a stable attribute such as eye color, hair color, age cues, family relationship, affiliation, ownership, location identity, or other enduring facts, compare it against the current chapter and flag any direct mismatch as a contradiction watchlist item.",
    "If the current chapter gives a new fact that conflicts with related canon, preserve both sides explicitly instead of merging or averaging them.",
    "Do not create a watchlist item or entity that is supported only by related canon when the current chapter does not reference that subject at all.",
    "If related canon helps interpret a chapter mention, keep the summary and watchlist anchored to what this chapter actually references.",
    "Each chronology item must represent one distinct event only.",
    "Each chronology label should be a relative sequence marker, and each chronology body should use bullet fields for Event, Location, Characters involved, Consequences, and Sources.",
    "Watchlist entries must use only these types: contradiction, missing-description, name-collision, timeline-risk, relationship-ambiguity, item-clarification, location-risk.",
    "Use contradiction for direct fact mismatches between chapter text and related canon.",
    "Do not use contradiction for simple lack of detail, thin evidence, or open questions unless two claims actually conflict.",
    "Use name-collision or location-risk when an ambiguous name could refer to more than one entity or category.",
    "Prefer a watchlist entry over a speculative entity classification or speculative merge.",
    "For contradiction watchlist entries, explicitly include: Subject, Conflicting claims, Source A, Source B, Notes, and Suggested status.",
    "Each watchlist body should use short bullet fields that explain the issue, what is missing or conflicting, and the source basis.",
    "Every factual summary and watchlist claim must remain traceable to chapter text or clearly labeled related canon. If multiple sources support a claim, list them. If support comes only from related canon, say that clearly and do not present it as established by this chapter.",
    "Keep wording dry, exact, compact, and audit-friendly.",
    "Return valid JSON only.",
    "Do not wrap the JSON in markdown code fences.",
    "Do not add commentary before or after the JSON.",
    `Chapter title: ${chapter.title}`,
    `Chapter text:\n${chapter.currentText}`,
    `Related canon context:\n${relatedCanon.join("\n")}`,
  ].join("\n\n");
}
