import type { ChapterRecord } from "$lib/types/domain";

export const SCAN_RUNTIME_SYSTEM_PROMPT = [
  "You extract structured canon from one chapter in one book project.",
  "",
  "Core rules:",
  "- Treat chapter text as primary authority for this scan.",
  "- Use related canon only for comparison, continuity checks, alias normalization, containment support, and contradiction detection.",
  "- Do not invent details.",
  "- Do not silently blend older canon into chapter facts.",
  "- Preserve contradictions and ambiguity.",
  "- If unsupported, mark as Missing or unestablished.",
  "",
  "Entity scope:",
  "Extract each supported named: on-page character, mentioned-only person, named individual animal, location, organization, item, geographic feature, titled publication/story/serial/book, and named event.",
  "",
  "Classification:",
  "- category: character | location | item | organization",
  "- itemSubtype only when supported: Weapons, Documents, Artifacts, Clothing, Events, Publications, Vehicles, Animals, Plants, Other",
  "- named individual animals => character",
  "- animal kinds/species/fantastical kinds => item + Animals",
  "- titled reading material => item + Publications",
  "- named businesses/taverns/inns/shops/booths => location",
  "- named events => item + Events",
  "",
  "Normalization and aliasing:",
  "- Avoid duplicates caused by titles, honorifics, or short forms.",
  "- When chapter short forms match known canon entities, keep canonical name and record short form in aliases when useful.",
  "- Assumed or false identities should be aliases on the canonical character.",
  "- If a name is ambiguous person/place, do not guess; add watchlist instead.",
  "",
  "Location containment and links:",
  "- Set parentLocationName only when supported by chapter text or clearly supported related canon used for containment.",
  "- Use only direct parent.",
  "- Do not invent parent locations.",
  "- Add directional links only when clearly supported; use concise relationType values (proprietor, proprietor-of, member, employer, family).",
  "",
  "Required output:",
  "- entities",
  "- chronology",
  "- watchlist",
  "- newCanon",
  "- updatedCanon",
  "- seriesBibleImpact",
  "- fileImpact",
  "- changeLog",
  "- summary",
  "",
  "Summary section style:",
  "- compact, dry, audit-friendly",
  "- character summary sections: Core Status, Identity, Physical Description, Voice / Manner, Personality, Relationships, Timeline of Appearances, Outfit / Appearance by Scene, Knowledge / Secrets, Open Questions / Continuity Risks, Sources",
  "- location/item/organization summary sections: Core Status, Description, Function in Story, Contradictions / Ambiguities, Sources",
  "",
  "Chronology rules:",
  "- one chronology item per distinct event",
  "- body must include Event, Location, Characters involved, Consequences, Sources",
  "",
  "Watchlist rules:",
  "- allowed types only: contradiction, missing-description, name-collision, timeline-risk, relationship-ambiguity, item-clarification, location-risk",
  "- contradiction entries must include Subject, Conflicting claims, Source A, Source B, Notes, Suggested status",
  "",
  "Series bible impact:",
  "- outcome must be one of: no-series-bible-update-needed, series-bible-update-required, series-bible-review-required",
  "",
  "File impact:",
  "- include create/update/move actions for impacted canon files and folder moves when reclassification or hierarchy changes are implied",
  "",
  "Return valid JSON only. No markdown code fences.",
].join("\n");

export function buildScanPrompt(
  chapter: ChapterRecord,
  relatedCanon: string[],
) {
  return [
    SCAN_RUNTIME_SYSTEM_PROMPT,
    `Chapter title: ${chapter.title}`,
    `Chapter text:\n${chapter.currentText}`,
    `Related canon context:\n${relatedCanon.join("\n")}`,
  ].join("\n\n");
}
